### ISSUE TITLE
Tip calculator split behavior could be adjusted or reworded

### ISSUE THREAD

**Issue by lainvineyard** [JeremyChaney/100-days-of-py#1]
In https://github.com/JeremyChaney/100-days-of-py/blob/0fe731a72de2ba42f88c997cb9185efdfd58f605/tip-calculator#L5, the tip calculator asks the user to input a number how many people they want to split their bill with---one way of reading this is "how many people (besides me) am I splitting the bill with." 

However, at this time the calculator uses exactly the number input as the total number of people to split their bill with which could cause quite the embarrassing moment at the table when the user tries to pay their portion of the check.

It would make sense to either reword the input prompt to ask for the total number of people that will be splitting the bill, or adjusting the calculator so it adds +1 to the number input for this prompt.

**Comment by JeremyChaney** [comment]
I updated the  "split" input to be more succinct and removed general snark.

**Comment by lainvineyard** [comment]
Looks good! Make sure to close this issue since it's been resolved 🎉

Note that if you include the commit hash that closes this issue, it will link to that commit and can be a good way to track when and where things were fixed

**Comment by JeremyChaney** [comment]
Done!

**Comment by lainvineyard** [comment]
niiiice
